### ISSUE TITLE
Line 36 error?

### ISSUE THREAD

**Issue by tethragon** [toadjaune/pulseaudio-config#12]
In the pulse setup.sh, line 36 is:

pactl load-module module-loopback source=virtual1.monitor sink="${SPEAKERS}" latency_msec=1 >> "${module_file}"

I think it should be:

pactl load-module module-loopback **source="${SPEAKERS}".monitor** sink=**virtual1** latency_msec=1 >> "${module_file}"

Am I wrong?

**Comment by toadjaune** [comment]
I'm pretty sure you don't want to send your speaker's output anywhere besides your speaker, because it includes the videoconference output, and that would send people's voice back to them.

I feel like you're getting confused as to how we're trying to set the devices up, here. Can you have another look at the schema's README ?

(related to #11 )

**Comment by tethragon** [comment]
OK I'll try to understand it better. Maybe I am confused. I'll do some more testing. Thanks for the answer.
