### ISSUE TITLE
pavucontrol settings problems

### ISSUE THREAD

**Issue by bonushenricus** [toadjaune/pulseaudio-config#13]
Hi
I have to do a lesson with students, part in presence part online
and the lesson includes videos that will be played by VLC.
The online students will be on google meet, which I run from Chrome.
The O.S. is Debian 11.

 - I setting pavucontrol with:
    - playback:
      -  ALSA plug-in VLC to virtual1
      -  Playback from Chrome to internal audio
      - Loopback from virtual1's monitor (with microphone icon) to internal audio
      - Loopback from virtual1's monitor (also with microphone icon) to virtual2
      - Loopback from Internal Audio (with card icon) to virtual1 (??)
    - recorder:
      - Chrome RecordStream input to virtual2Mic
      - Loopback to Internal Audio (card icon) from virtual1's Monitor
      - Loopback to virtual2 (card icon) from monitor of virtual1
      - Loopback to virtual1 (card icon and hear microphone ??) from Internal Audio
      - Virtual Source Stream of virtual2Mic from Monitor of virtual2
 - I setting google meet settings:
     - microphone: virtual2mic
     - speakers: virtual1
 - I setting vlc
     -  audio preferences to PulseAudio output 

I must have done something wrong: I can't hear it either in presence or online.
What did I do wrong?

Thank you

**Comment by toadjaune** [comment]
Hmmm, I can't see anything wrong with the setup you're describing, although it's a bit hard to visualize with such an enumeration.

I'd recommend trying to manually change stuff around in pavucontrol, and see what works or not, like, sending vlc's output directly to your speakers, bypassing the virtual devices, etc.

I'm afraid I won't be of much more use than that, I haven't used this setup in years (and don't actually have an actual pulseaudio on my machines anymore, since they switched to pipewire ^^)

Best of luck for you debug !
